### ISSUE TITLE
Can't run your program

### ISSUE THREAD

**Issue by phanlong2811** [mossbee/Instagram_white_square_border_adder#1]
It seems you are using a file isn't in repo in file add_border.py. Please push this to repo!
![image](https://github.com/mossbee/Instagram_white_square_border_adder/assets/44520002/e02bd61e-90d6-4d68-96be-920be3d6b871)

**Comment by mossbee** [comment]
Solved

**Comment by mossbee** [comment]
Solved, the new add_border1.py should work
